food_categories = {
    "vegetables": [
        "artichoke", "arugula", "asparagus", "bamboo shoots", "beetroot", "bell pepper",
        "bok choy", "broccoli", "brussels sprouts", "butternut squash", "cabbage", "carrot",
        "cauliflower", "celery", "chayote", "chicory", "collard greens", "corn", "cucumber",
        "daikon", "dill", "edamame", "eggplant", "endive", "fennel", "garlic", "ginger",
        "green beans", "horseradish", "jicama", "kale", "kohlrabi", "leek", "lettuce",
        "mushroom", "mustard greens", "napa cabbage", "okra", "onion", "parsnip", "peas",
        "peppers", "potato", "pumpkin", "radicchio", "radish", "rhubarb", "rutabaga",
        "scallion", "shallot", "snow peas", "spinach", "sprouts", "squash", "sweet potato",
        "swiss chard", "taro", "tomatillo", "tomato", "turnip", "watercress", "yam", "zucchini",
        "seaweed", "lotus root", "chard", "broccolini", "fiddlehead", "chervil", "chives",
        "mizuna", "purslane", "samphire", "sorrel", "tatsoi", "wasabi", "water spinach",
        "winter melon", "yuca", "black radish", "celtuce", "scorzonera", "cardoon", "malabar spinach",
        "amaranth leaves", "gobo", "garbanzo leaves", "fenugreek leaves", "perilla", "salsify", "crosne",
        "rampion", "pepperwort", "tree spinach", "sea kale", "agati", "mallow", "elephant garlic"
    ],
    "meat": [
        "beef", "pork", "lamb", "veal", "goat", "chicken", "duck", "turkey", "quail", "pheasant",
        "rabbit", "venison", "bison", "boar", "elk", "horse", "kangaroo", "guinea fowl", "partridge",
        "pigeon", "squab", "emu", "ostrich", "reindeer", "yak", "moose", "bear", "wild boar",
        "mutton", "frog legs", "alligator", "snake", "turtle", "opossum", "armadillo", "beaver",
        "camel", "goose", "grouse", "dove", "cornish hen", "rocky mountain oysters", "snipe",
        "woodcock", "lizard", "antelope", "ibex", "caribou", "porcupine", "nutria", "muskrat",
        "bushmeat", "iguana", "shark", "whale", "seal", "yakitori", "sweetbreads", "tripe",
        "ox", "offal", "giblets", "head cheese", "blood sausage", "liver", "heart", "kidney",
        "tongue", "lungs", "marrow", "spleen", "chitlins", "pork belly", "flank steak", "tenderloin",
        "sirloin", "ribeye", "porterhouse", "t-bone", "chuck roast", "brisket", "short ribs",
        "oxtail", "skirt steak", "hanger steak", "shoulder", "shank", "hocks", "rump", "round",
        "filet mignon", "ground beef", "pancetta", "prosciutto", "salami", "bacon", "ham"
    ],
    "fruits": [
        "apple", "apricot", "avocado", "banana", "blackberry", "blueberry", "boysenberry",
        "cantaloupe", "cherry", "clementine", "coconut", "cranberry", "currant", "date",
        "dragon fruit", "durian", "elderberry", "fig", "gooseberry", "grape", "grapefruit",
        "guava", "honeydew", "jackfruit", "jambul", "jujube", "kiwi", "kumquat", "lemon",
        "lime", "longan", "loquat", "lychee", "mango", "mandarin", "mulberry", "nectarine",
        "olive", "orange", "papaya", "passion fruit", "peach", "pear", "persimmon", "pineapple",
        "plum", "pomegranate", "pomelo", "prickly pear", "quince", "raspberry", "red currant",
        "salak", "satsuma", "soursop", "star fruit", "strawberry", "tamarillo", "tamarind",
        "tangerine", "ugli fruit", "watermelon", "white currant", "yumberry", "black sapote",
        "ackee", "bilberry", "breadfruit", "canistel", "chico fruit", "cloudberry", "feijoa",
        "finger lime", "genip", "grumichama", "ice apple", "jabuticaba", "kiwano", "mamey sapote",
        "mangosteen", "miracle fruit", "nance", "nutmeg fruit", "pulasan", "rambutan",
        "santol", "soursop", "surinam cherry", "tangelo", "yangmei"
    ],
    "dairy": [
        "milk", "cheese", "butter", "yogurt", "cream", "ghee", "curd", "kefir",
        "sour cream", "cottage cheese", "whipped cream", "clotted cream", "evaporated milk",
        "condensed milk", "powdered milk", "buttermilk", "whey", "ricotta", "mozzarella",
        "cheddar", "parmesan", "gorgonzola", "brie", "camembert", "roquefort", "stilton",
        "feta", "paneer", "halloumi", "provolone", "swiss cheese", "gouda", "edam", "colby",
        "monterey jack", "havarti", "emmental", "gruyère", "blue cheese", "pepper jack",
        "queso fresco", "queso blanco", "chèvre", "fontina", "muenster", "mascarpone",
        "neufchâtel", "double cream", "triple cream", "marscapone", "caciocavallo",
        "burrata", "buffalo mozzarella", "quark", "smetana", "labneh", "dairy creamer",
        "butterfat", "ice cream", "ymer", "vla", "khoa", "serek", "rømme", "crème fraîche",
        "lactose-free milk", "sheep milk", "goat milk", "buffalo milk", "a2 milk"
    ],
    "seafood": [
        "abalone", "anchovy", "bass", "barramundi", "catfish", "clam", "cod", "crab",
        "crawfish", "cuttlefish", "eel", "flounder", "grouper", "haddock", "halibut",
        "herring", "lobster", "mackerel", "mahi-mahi", "mussels", "octopus", "oyster",
        "perch", "pollock", "pompano", "salmon", "sardine", "scallop", "shrimp", "snapper",
        "squid", "swordfish", "tilapia", "trout", "tuna", "turbot", "whiting", "whitefish",
        "kingfish", "amberjack", "bluefish", "monkfish", "pike", "sturgeon", "tarpon"
    ],
    "condiments/ingredients" : [
    "salt", "pepper", "chili powder", "cumin", "coriander", "turmeric", "garlic powder", 
    "onion powder", "ginger", "cinnamon", "nutmeg", "clove", "cardamom", "allspice", 
    "mustard", "fennel", "bay leaves", "oregano", "thyme", "basil", "rosemary", "sage", 
    "marjoram", "dill", "parsley", "tarragon", "chives", "vanilla", "almond extract", 
    "maple syrup", "honey", "molasses", "sugar", "agave syrup", "stevia", "baking soda", 
    "baking powder", "cornstarch", "yeast", "gelatin", "pectin", "vinegar", "soy sauce", 
    "fish sauce", "oyster sauce", "Worcestershire sauce", "hoisin sauce", "teriyaki sauce", 
    "hot sauce", "mustard", "ketchup", "mayonnaise", "BBQ sauce", "ranch dressing", 
    "Caesar dressing", "Italian dressing", "sesame oil", "olive oil", "vegetable oil", 
    "canola oil", "peanut oil", "coconut oil", "avocado oil", "grapeseed oil", "butter", 
    "ghee", "shortening", "lard", "cream", "evaporated milk", "condensed milk", "cocoa powder", 
    "chocolate", "soy lecithin", "miso", "tahini", "peanut butter", "almond butter", 
    "coconut milk", "seeds", "flour", "rice", "pasta", "noodles", "lentils", "beans", 
    "chickpeas", "peas", "cornmeal", "oats", "quinoa", "barley", "bulgur", "couscous", 
    "polenta", "breadcrumbs", "stock", "broth", "arrowroot", "gelatin", "tapioca", 
    "nutmeg", "anise", "saffron", "fenugreek", "curry powder", "horseradish", "wasabi", 
    "sesame", "poppy seeds", "chia seeds", "flax seeds"
    ]
}